codecov:
  require_ci_to_pass: true

ignore:
  - "**/test_utils.rs"
  - "**/test_utils/**"
  - "**/tests.rs"
  - "**/tests/**"
  - "fuzz/**"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: "condensed_header, diff, flags, components, condensed_files"
  behavior: default
  require_changes: true

component_management:
  individual_components:
    - component_id: grovedb-core
      name: grovedb-core
      paths:
        - grovedb/
    - component_id: merk
      name: merk
      paths:
        - merk/
    - component_id: storage
      name: storage
      paths:
        - storage/
    - component_id: commitment-tree
      name: commitment-tree
      paths:
        - grovedb-commitment-tree/
    - component_id: mmr
      name: mmr
      paths:
        - grovedb-merkle-mountain-range/
    - component_id: bulk-append-tree
      name: bulk-append-tree
      paths:
        - grovedb-bulk-append-tree/
    - component_id: element
      name: element
      paths:
        - grovedb-element/

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: core
      paths:
        - costs/
        - path/
        - visualize/
        - grovedb-version/
        - grovedbg-types/
        - storage/
        - grovedb-epoch-based-storage-flags/
        - grovedb-element/
        - merk/
        - grovedb-query/
    - name: trees
      paths:
        - grovedb-merkle-mountain-range/
        - grovedb-dense-fixed-sized-merkle-tree/
        - grovedb-bulk-append-tree/
        - grovedb-commitment-tree/
    - name: grovedb
      paths:
        - grovedb/
