//! Proof generation and verification for `CountIndexedTree` top-k and
//! count-range queries.
//!
//! The proof envelope binds three pieces:
//! 1. A chain of single-key Merk proofs from the GroveDB root down to the
//!    parent Merk of the `CountIndexedTree` element, ending with a proof
//!    of the cidx element's existence.
//! 2. A 32-byte attestation of the cidx primary's root hash. The primary
//!    is not traversed by these queries, but its root hash participates in
//!    the H1-A `combined_value_hash` of the cidx element and so must be
//!    available to the verifier.
//! 3. A standard Merk range proof against the cidx **secondary**, which
//!    yields the top-k / range entries and the secondary's root hash.
//!
//! The verifier reconstructs
//! `combine_hash_three(value_hash(cidx_element_bytes), primary_root_hash,
//! secondary_root_hash)` and checks it equals the value_hash recorded for
//! the cidx key by its parent Merk. That single check binds the secondary
//! range proof to the GroveDB root hash via the H1-A composition we
//! ratified in design (chapter "The CountIndexedTree", H1-A).
//!
//! No batch / cross-subtree integration with the existing GroveDBProof
//! envelope yet — this is a standalone proof shape, decoded only by the
//! dedicated `verify_count_indexed_*` entry points.

use bincode::{Decode, Encode};
use grovedb_costs::{
    cost_return_on_error, cost_return_on_error_no_add, CostResult, CostsExt, OperationCost,
};
use grovedb_merk::{
    element::get::ElementFetchFromStorageExtensions,
    proofs::{query::QueryProofVerify, Query as MerkQuery},
    tree::{combine_hash, combine_hash_three, value_hash, CryptoHash},
};
use grovedb_path::{SubtreePath, SubtreePathBuilder};
use grovedb_query::QueryItem as MerkQueryItem;
use grovedb_storage::StorageBatch;
use grovedb_version::version::GroveVersion;

use crate::{util::TxRef, Element, Error, GroveDb, Transaction, TransactionArg};

/// Wire-format envelope for a `CountIndexedTree` top-k / count-range
/// proof. Layered proofs (`layer_proofs[i]`) walk the GroveDB hierarchy
/// from the root toward the cidx element; `layer_proofs.last()` is the
/// deepest single-key proof, which proves the cidx element's existence
/// in its parent Merk.
#[derive(Encode, Decode, Debug)]
pub struct CountIndexedRangeProof {
    /// Single-key Merk proof per path layer, top-down.
    /// `layer_proofs[i]` is generated by opening the Merk at `path[..i]`
    /// and proving the existence of `path[i]`.
    pub layer_proofs: Vec<Vec<u8>>,
    /// 32-byte attestation of the cidx primary's root hash. Carried by
    /// the proof because the verifier needs it to reconstruct the H1-A
    /// composition but does not traverse the primary itself.
    pub primary_root_hash: [u8; 32],
    /// Per-intermediate-layer cidx secondary attestation, length =
    /// `layer_proofs.len() - 1`. For depth `d` in
    /// `0..layer_proofs.len() - 1`, `Some(secondary_root_hash)` means
    /// the element at `path[..d+1]` is itself a cidx — its merk node's
    /// `value_hash` was composed with `combine_hash_three(value_hash,
    /// primary_root, secondary_root)`. The verifier uses
    /// `current_layer_root` (root hash of layer `d+1`'s merk) as the
    /// primary_root and this attestation as the secondary_root.
    /// `None` means the layer's element is a regular tree and chains
    /// via the standard `combine_hash`.
    pub ancestor_cidx_secondary_root_hashes: Vec<Option<[u8; 32]>>,
    /// Encoded Merk range proof for the cidx secondary. Verified
    /// independently with the existing `Query::execute_proof` API; yields
    /// the secondary's root hash and the (count_be ‖ key) entries.
    pub secondary_proof: Vec<u8>,
    /// Echoed query limit. The verifier uses this to interpret the
    /// secondary proof's bounded-vs-unbounded shape, AND the caller
    /// must supply an expected limit so the verifier rejects an
    /// envelope whose limit doesn't match the requested semantics.
    /// `None` is distinct from `Some(0)`: `None` means "no limit"
    /// while `Some(0)` means "limit zero results" (degenerate).
    pub requested_limit: Option<u16>,
    /// Echoed iteration direction. `false` = ascending (left-to-right
    /// over secondary keys, lowest counts first); `true` = descending
    /// (highest counts first). The caller-facing verify entry points
    /// take an `expected_descending` argument; the verifier rejects
    /// any envelope whose direction doesn't match, so a malicious
    /// prover cannot answer a top-k request with a valid bottom-k
    /// proof (same root, same path, different semantics).
    pub descending: bool,
}

/// Verified result of a `CountIndexedTree` top-k or count-range query.
#[derive(Debug)]
pub struct CountIndexedQueryResult {
    /// GroveDB root hash this proof reconstructs.
    pub root_hash: CryptoHash,
    /// `(count_value, original_key)` pairs from the secondary, in the
    /// order they were proven. Caller is responsible for any further
    /// limit/range filtering beyond what the proof carries.
    pub entries: Vec<(u64, Vec<u8>)>,
}

/// Wire-format envelope for an offset-paginated `CountIndexedTree`
/// top-k proof.
///
/// Structurally parallel to [`CountIndexedRangeProof`] — same layer
/// proofs + primary-root attestation + ancestor-cidx attestations —
/// but the `secondary_proof` is the **count-offset paginated proof**
/// shape produced by
/// `Merk::prove_count_offset_on_range(QueryItem::RangeFull, offset, ...)`
/// against the cidx secondary (a `ProvableCountTree`). The skipped
/// region collapses to `HashWithCount` ops so the proof is O(log n
/// + k) regardless of offset, rather than O(offset + k) for a
/// naively-paged range proof.
#[derive(Encode, Decode, Debug)]
pub struct CountIndexedPaginatedProof {
    /// Single-key Merk proof per path layer, top-down. Same shape and
    /// semantics as [`CountIndexedRangeProof::layer_proofs`].
    pub layer_proofs: Vec<Vec<u8>>,
    /// 32-byte attestation of the cidx primary's root hash. Same
    /// semantics as [`CountIndexedRangeProof::primary_root_hash`].
    pub primary_root_hash: [u8; 32],
    /// Per-intermediate-layer cidx secondary attestation. Same
    /// semantics as
    /// [`CountIndexedRangeProof::ancestor_cidx_secondary_root_hashes`].
    pub ancestor_cidx_secondary_root_hashes: Vec<Option<[u8; 32]>>,
    /// Encoded count-offset paginated proof bytes for the cidx
    /// secondary. Verified with `verify_count_offset_on_range_proof`
    /// against `QueryItem::RangeFull` + the echoed offset/limit/dir.
    pub secondary_proof: Vec<u8>,
    /// Echoed query parameters. The verifier authenticates these
    /// against the caller's expected values; any mismatch is rejected
    /// before the merk-level proof is even decoded.
    pub requested_k: u16,
    /// Echoed offset. Verifier rejects on mismatch.
    pub requested_offset: u64,
    /// Echoed iteration direction (`true` = descending, highest counts
    /// first). Verifier rejects on mismatch.
    pub descending: bool,
}

/// Verified result of an offset-paginated `CountIndexedTree` top-k
/// query.
///
/// `entries` are the `(count_value, original_key)` pairs the prover
/// returned **after** skipping `skipped` items (the verifier
/// independently re-derives `skipped` from the proof shape — it is
/// not a prover-trusted field). The caller MUST cross-check
/// `skipped == expected_offset` if exact-page semantics matter
/// (e.g., for short-circuiting "no more pages"): a fresh insert may
/// have made the proof produce fewer in-range entries than the
/// caller expected.
#[derive(Debug)]
pub struct CountIndexedPaginatedResult {
    /// GroveDB root hash this proof reconstructs.
    pub root_hash: CryptoHash,
    /// `(count_value, original_key)` pairs from the secondary, in the
    /// order they were proven (after the `skipped` offset region).
    pub entries: Vec<(u64, Vec<u8>)>,
    /// Number of secondary entries the proof committed as skipped
    /// (via `HashWithCount` ops). Independently re-derived by the
    /// verifier from the merk proof shape — NOT trusted from the
    /// prover's echoed `requested_offset`.
    pub skipped: u64,
}

impl GroveDb {
    /// Generate a proof for the top-`k` entries of a `CountIndexedTree`,
    /// ordered by `count_value`. Thin wrapper around
    /// [`Self::prove_count_indexed_query`] with a full-range secondary
    /// query.
    pub fn prove_count_indexed_top_k<'b, B, P>(
        &self,
        path: P,
        k: u16,
        descending: bool,
        transaction: TransactionArg,
        grove_version: &GroveVersion,
    ) -> CostResult<Vec<u8>, Error>
    where
        B: AsRef<[u8]> + 'b,
        P: Into<SubtreePath<'b, B>>,
    {
        let mut full_range = MerkQuery::new();
        full_range.insert_all();
        full_range.left_to_right = !descending;
        self.prove_count_indexed_query(path, full_range, Some(k), transaction, grove_version)
    }

    /// Generate an offset-paginated proof for the top-`k` entries of a
    /// `CountIndexedTree`, ordered by `count_value`, starting **after**
    /// `offset` entries in the directional walk.
    ///
    /// Functionally equivalent to skipping the first `offset` results
    /// from [`Self::prove_count_indexed_top_k`], but the skipped region
    /// is committed via the merk-level count-offset proof flow
    /// (`prove_count_offset_on_range` against the secondary, which IS
    /// a `ProvableCountTree`). The skipped region collapses to
    /// `HashWithCount` ops so the proof is O(log n + k) regardless of
    /// `offset`.
    ///
    /// Use [`Self::verify_count_indexed_top_k_paginated`] to verify
    /// the resulting bytes. The verifier authenticates the echoed
    /// `k` / `offset` / `descending` against caller expectations
    /// before walking the proof, so an honest paginated request
    /// cannot be answered with a different page's proof.
    pub fn prove_count_indexed_top_k_paginated<'b, B, P>(
        &self,
        path: P,
        k: u16,
        offset: u64,
        descending: bool,
        transaction: TransactionArg,
        grove_version: &GroveVersion,
    ) -> CostResult<Vec<u8>, Error>
    where
        B: AsRef<[u8]> + 'b,
        P: Into<SubtreePath<'b, B>>,
    {
        let mut cost = OperationCost::default();
        let path: SubtreePath<B> = path.into();
        let batch = StorageBatch::new();
        let tx = TxRef::new(&self.db, transaction);
        let tx_ref = tx.as_ref();

        let envelope = cost_return_on_error!(
            &mut cost,
            self.build_count_indexed_paginated_proof(
                path,
                k,
                offset,
                descending,
                tx_ref,
                &batch,
                grove_version,
            )
        );

        let bytes = cost_return_on_error_no_add!(
            cost,
            bincode::encode_to_vec(&envelope, bincode::config::standard())
                .map_err(|e| Error::CorruptedData(format!("encoding cidx paginated proof: {e}")))
        );

        Ok(bytes).wrap_with_cost(cost)
    }

    /// Generate a proof for an arbitrary query over a `CountIndexedTree`'s
    /// **secondary** index keyspace. Secondary keys are
    /// `(count_value_be ‖ original_key)`; callers can express any
    /// predicate that fits the standard `MerkQuery` shape (single keys,
    /// prefix ranges, multi-range, ascending or descending) by building
    /// the query in those bytes.
    ///
    /// The encoded envelope binds:
    /// - the chain of single-key Merk proofs from the GroveDB root to the
    ///   cidx element's parent merk;
    /// - the cidx primary's root hash (attestation needed by the H1-A
    ///   verifier);
    /// - per-cidx-ancestor secondary attestation when the path traverses
    ///   nested cidx (so verifier uses `combine_hash_three` at those
    ///   layers);
    /// - a standard Merk range proof of `secondary_query` against the
    ///   cidx secondary, with the `limit` if any.
    ///
    /// Verify with [`Self::verify_count_indexed_query`] using the same
    /// `secondary_query`.
    pub fn prove_count_indexed_query<'b, B, P>(
        &self,
        path: P,
        secondary_query: MerkQuery,
        limit: Option<u16>,
        transaction: TransactionArg,
        grove_version: &GroveVersion,
    ) -> CostResult<Vec<u8>, Error>
    where
        B: AsRef<[u8]> + 'b,
        P: Into<SubtreePath<'b, B>>,
    {
        let mut cost = OperationCost::default();
        let path: SubtreePath<B> = path.into();
        let batch = StorageBatch::new();
        let tx = TxRef::new(&self.db, transaction);
        let tx_ref = tx.as_ref();

        let envelope = cost_return_on_error!(
            &mut cost,
            self.build_count_indexed_proof(
                path,
                secondary_query,
                limit,
                tx_ref,
                &batch,
                grove_version,
            )
        );

        let bytes = cost_return_on_error_no_add!(
            cost,
            bincode::encode_to_vec(&envelope, bincode::config::standard())
                .map_err(|e| Error::CorruptedData(format!("encoding cidx proof: {e}")))
        );

        Ok(bytes).wrap_with_cost(cost)
    }

    fn build_count_indexed_proof<'db, 'b, B: AsRef<[u8]>>(
        &'db self,
        path: SubtreePath<'b, B>,
        secondary_query: MerkQuery,
        limit: Option<u16>,
        transaction: &'db Transaction,
        batch: &'db StorageBatch,
        grove_version: &GroveVersion,
    ) -> CostResult<CountIndexedRangeProof, Error> {
        let mut cost = OperationCost::default();

        // Collect path keys and parent paths for layer-by-layer proof.
        let path_keys: Vec<Vec<u8>> = path.to_vec();
        if path_keys.is_empty() {
            return Err(Error::InvalidPath(
                "cannot prove count-indexed query at root path".to_string(),
            ))
            .wrap_with_cost(cost);
        }

        // 1. Build a single-key Merk proof at each layer (top-down).
        //
        //    For each intermediate depth `d` (`d < last_idx`), if the
        //    element at `path[..d+1]` is itself a CountIndexedTree,
        //    capture its secondary root hash as an attestation; the
        //    verifier needs it to chain via `combine_hash_three` at that
        //    layer (cidx ancestors compose with three inputs, not two).
        let mut layer_proofs: Vec<Vec<u8>> = Vec::with_capacity(path_keys.len());
        let last_idx = path_keys.len() - 1;
        let mut ancestor_cidx_secondary_root_hashes: Vec<Option<[u8; 32]>> =
            Vec::with_capacity(last_idx);
        for depth in 0..path_keys.len() {
            // The Merk at path[..depth] proves the existence of
            // path_keys[depth].
            let parent_slices: Vec<&[u8]> =
                path_keys[..depth].iter().map(|p| p.as_slice()).collect();
            let parent_path: SubtreePath<&[u8]> = parent_slices.as_slice().into();
            let parent_merk = cost_return_on_error!(
                &mut cost,
                self.open_transactional_merk_at_path(
                    parent_path.clone(),
                    transaction,
                    Some(batch),
                    grove_version,
                )
            );
            let key = path_keys[depth].clone();
            if depth < last_idx {
                let intermediate = cost_return_on_error!(
                    &mut cost,
                    Element::get(&parent_merk, key.as_slice(), true, grove_version).map_err(|e| {
                        Error::CorruptedData(format!(
                            "cidx proof: fetch intermediate-layer element at depth {depth}: {e}"
                        ))
                    })
                );
                let attestation = match intermediate.underlying() {
                    Element::CountIndexedTree(..) | Element::ProvableCountIndexedTree(..) => {
                        // Open this ancestor cidx's secondary and capture
                        // its current root hash for the attestation.
                        let ancestor_cidx_path_owned: SubtreePathBuilder<Vec<u8>> =
                            SubtreePathBuilder::owned_from_iter(
                                path_keys[..=depth].iter().cloned(),
                            );
                        let ancestor_cidx_path = SubtreePath::from(&ancestor_cidx_path_owned);
                        let ancestor_secondary_root_key = match intermediate.underlying() {
                            Element::CountIndexedTree(_, s, ..)
                            | Element::ProvableCountIndexedTree(_, s, ..) => s.clone(),
                            _ => unreachable!(),
                        };
                        let ancestor_secondary = cost_return_on_error!(
                            &mut cost,
                            self.open_count_indexed_secondary_at_path(
                                ancestor_cidx_path,
                                ancestor_secondary_root_key,
                                transaction,
                                Some(batch),
                                grove_version,
                            )
                        );
                        let (sec_hash, _, _) = cost_return_on_error!(
                            &mut cost,
                            ancestor_secondary
                                .root_hash_key_and_aggregate_data()
                                .map_err(|e| Error::CorruptedData(format!(
                                    "cidx proof: ancestor secondary root hash at depth {depth}: {e}"
                                )))
                        );
                        Some(sec_hash)
                    }
                    _ => None,
                };
                ancestor_cidx_secondary_root_hashes.push(attestation);
            }
            let mut q = MerkQuery::new();
            q.insert_item(MerkQueryItem::Key(key));
            let result = cost_return_on_error!(
                &mut cost,
                parent_merk
                    .prove(q, None, grove_version)
                    .map_err(|e| Error::CorruptedData(format!(
                        "cidx proof: prove single-key at layer depth {depth}: {e}"
                    )))
            );
            layer_proofs.push(result.proof);
        }

        // 2. Open primary at path; capture its root hash for attestation.
        let primary_merk = cost_return_on_error!(
            &mut cost,
            self.open_transactional_merk_at_path(
                path.clone(),
                transaction,
                Some(batch),
                grove_version,
            )
        );
        if !primary_merk.tree_type.is_count_indexed_primary() {
            return Err(Error::InvalidPath(
                "prove_count_indexed_top_k requires the path's last segment to be a \
                 CountIndexedTree element"
                    .to_string(),
            ))
            .wrap_with_cost(cost);
        }
        let (primary_root_hash, _, _) = cost_return_on_error!(
            &mut cost,
            primary_merk
                .root_hash_key_and_aggregate_data()
                .map_err(|e| Error::CorruptedData(format!("cidx proof: primary root hash: {e}")))
        );

        // 3. Open secondary; produce a range proof in the requested
        //    direction with limit = k.
        let secondary_root_key = cost_return_on_error!(
            &mut cost,
            self.read_count_indexed_secondary_root_key_for_proof(
                path.clone(),
                transaction,
                Some(batch),
                grove_version,
            )
        );
        let secondary_merk = cost_return_on_error!(
            &mut cost,
            self.open_count_indexed_secondary_at_path(
                path,
                secondary_root_key,
                transaction,
                Some(batch),
                grove_version,
            )
        );
        // Echo the user-supplied query parameters into the envelope.
        // The verifier authenticates these against the caller's
        // expected_limit / expected_descending; we preserve Option
        // semantics for the limit (no None↔0 conflation).
        let descending = !secondary_query.left_to_right;
        let requested_limit = limit;
        let sec_result = cost_return_on_error!(
            &mut cost,
            secondary_merk
                .prove(secondary_query, limit, grove_version)
                .map_err(|e| Error::CorruptedData(format!(
                    "cidx proof: secondary range proof: {e}"
                )))
        );

        Ok(CountIndexedRangeProof {
            layer_proofs,
            primary_root_hash,
            ancestor_cidx_secondary_root_hashes,
            secondary_proof: sec_result.proof,
            requested_limit,
            descending,
        })
        .wrap_with_cost(cost)
    }

    /// Build an offset-paginated cidx top-k proof envelope. Shares the
    /// layer-walking + primary-attestation shape of
    /// [`Self::build_count_indexed_proof`] but produces the secondary
    /// half via `Merk::prove_count_offset_on_range` against
    /// `QueryItem::RangeFull` — the secondary is a `ProvableCountTree`,
    /// so the count-offset proof flow is valid against it directly.
    fn build_count_indexed_paginated_proof<'db, 'b, B: AsRef<[u8]>>(
        &'db self,
        path: SubtreePath<'b, B>,
        k: u16,
        offset: u64,
        descending: bool,
        transaction: &'db Transaction,
        batch: &'db StorageBatch,
        grove_version: &GroveVersion,
    ) -> CostResult<CountIndexedPaginatedProof, Error> {
        use grovedb_merk::proofs::{encode_into, query::QueryItem as MerkQueryItemForRange};

        let mut cost = OperationCost::default();

        let path_keys: Vec<Vec<u8>> = path.to_vec();
        if path_keys.is_empty() {
            return Err(Error::InvalidPath(
                "cannot prove count-indexed paginated query at root path".to_string(),
            ))
            .wrap_with_cost(cost);
        }

        // 1. Single-key Merk proof at each layer (top-down) plus per-cidx-
        //    ancestor secondary-root attestation. Identical shape to the
        //    non-paginated `build_count_indexed_proof` — see that
        //    function's comments for the per-step rationale.
        let mut layer_proofs: Vec<Vec<u8>> = Vec::with_capacity(path_keys.len());
        let last_idx = path_keys.len() - 1;
        let mut ancestor_cidx_secondary_root_hashes: Vec<Option<[u8; 32]>> =
            Vec::with_capacity(last_idx);
        for depth in 0..path_keys.len() {
            let parent_slices: Vec<&[u8]> =
                path_keys[..depth].iter().map(|p| p.as_slice()).collect();
            let parent_path: SubtreePath<&[u8]> = parent_slices.as_slice().into();
            let parent_merk = cost_return_on_error!(
                &mut cost,
                self.open_transactional_merk_at_path(
                    parent_path.clone(),
                    transaction,
                    Some(batch),
                    grove_version,
                )
            );
            let key = path_keys[depth].clone();
            if depth < last_idx {
                let intermediate = cost_return_on_error!(
                    &mut cost,
                    Element::get(&parent_merk, key.as_slice(), true, grove_version).map_err(|e| {
                        Error::CorruptedData(format!(
                            "cidx paginated proof: fetch intermediate-layer element at depth \
                             {depth}: {e}"
                        ))
                    })
                );
                let attestation = match intermediate.underlying() {
                    Element::CountIndexedTree(..) | Element::ProvableCountIndexedTree(..) => {
                        let ancestor_cidx_path_owned: SubtreePathBuilder<Vec<u8>> =
                            SubtreePathBuilder::owned_from_iter(
                                path_keys[..=depth].iter().cloned(),
                            );
                        let ancestor_cidx_path = SubtreePath::from(&ancestor_cidx_path_owned);
                        let ancestor_secondary_root_key = match intermediate.underlying() {
                            Element::CountIndexedTree(_, s, ..)
                            | Element::ProvableCountIndexedTree(_, s, ..) => s.clone(),
                            _ => unreachable!(),
                        };
                        let ancestor_secondary = cost_return_on_error!(
                            &mut cost,
                            self.open_count_indexed_secondary_at_path(
                                ancestor_cidx_path,
                                ancestor_secondary_root_key,
                                transaction,
                                Some(batch),
                                grove_version,
                            )
                        );
                        let (sec_hash, _, _) = cost_return_on_error!(
                            &mut cost,
                            ancestor_secondary
                                .root_hash_key_and_aggregate_data()
                                .map_err(|e| Error::CorruptedData(format!(
                                    "cidx paginated proof: ancestor secondary root hash at \
                                     depth {depth}: {e}"
                                )))
                        );
                        Some(sec_hash)
                    }
                    _ => None,
                };
                ancestor_cidx_secondary_root_hashes.push(attestation);
            }
            let mut q = MerkQuery::new();
            q.insert_item(MerkQueryItem::Key(key));
            let result = cost_return_on_error!(
                &mut cost,
                parent_merk
                    .prove(q, None, grove_version)
                    .map_err(|e| Error::CorruptedData(format!(
                        "cidx paginated proof: prove single-key at layer depth {depth}: {e}"
                    )))
            );
            layer_proofs.push(result.proof);
        }

        // 2. Open primary at path; capture its root hash for attestation.
        let primary_merk = cost_return_on_error!(
            &mut cost,
            self.open_transactional_merk_at_path(
                path.clone(),
                transaction,
                Some(batch),
                grove_version,
            )
        );
        if !primary_merk.tree_type.is_count_indexed_primary() {
            return Err(Error::InvalidPath(
                "prove_count_indexed_top_k_paginated requires the path's last segment to be a \
                 CountIndexedTree element"
                    .to_string(),
            ))
            .wrap_with_cost(cost);
        }
        let (primary_root_hash, _, _) = cost_return_on_error!(
            &mut cost,
            primary_merk
                .root_hash_key_and_aggregate_data()
                .map_err(|e| Error::CorruptedData(format!(
                    "cidx paginated proof: primary root hash: {e}"
                )))
        );

        // 3. Open secondary; produce a count-offset paginated proof
        //    against the full secondary range with limit = k.
        let secondary_root_key = cost_return_on_error!(
            &mut cost,
            self.read_count_indexed_secondary_root_key_for_proof(
                path.clone(),
                transaction,
                Some(batch),
                grove_version,
            )
        );
        let secondary_merk = cost_return_on_error!(
            &mut cost,
            self.open_count_indexed_secondary_at_path(
                path,
                secondary_root_key,
                transaction,
                Some(batch),
                grove_version,
            )
        );

        // The full-range query item the verifier will reuse. `descending
        // = true` maps to `left_to_right = false` for the merk-level
        // walk.
        let inner_range = MerkQueryItemForRange::RangeFull(std::ops::RangeFull);
        let prove_result = cost_return_on_error!(
            &mut cost,
            secondary_merk
                .prove_count_offset_on_range(
                    &inner_range,
                    offset,
                    Some(k as u64),
                    !descending,
                    grove_version,
                )
                .map_err(|e| Error::CorruptedData(format!(
                    "cidx paginated proof: secondary count-offset proof: {e}"
                )))
        );
        let mut serialized = Vec::with_capacity(128);
        encode_into(prove_result.ops.iter(), &mut serialized);

        Ok(CountIndexedPaginatedProof {
            layer_proofs,
            primary_root_hash,
            ancestor_cidx_secondary_root_hashes,
            secondary_proof: serialized,
            requested_k: k,
            requested_offset: offset,
            descending,
        })
        .wrap_with_cost(cost)
    }

    fn read_count_indexed_secondary_root_key_for_proof<'db, 'b, B: AsRef<[u8]>>(
        &'db self,
        path: SubtreePath<'b, B>,
        transaction: &'db Transaction,
        batch: Option<&'db StorageBatch>,
        grove_version: &GroveVersion,
    ) -> CostResult<Option<Vec<u8>>, Error> {
        let mut cost = OperationCost::default();
        let (parent_path, count_indexed_key) = match path.derive_parent() {
            Some(p) => p,
            None => {
                return Err(Error::InvalidPath(
                    "cannot prove count-indexed query at root path".to_string(),
                ))
                .wrap_with_cost(cost);
            }
        };
        let parent_merk = cost_return_on_error!(
            &mut cost,
            self.open_transactional_merk_at_path(parent_path, transaction, batch, grove_version)
        );
        let element = cost_return_on_error!(
            &mut cost,
            Element::get(&parent_merk, count_indexed_key, true, grove_version).map_err(|e| {
                Error::CorruptedData(format!(
                    "cidx proof: fetch cidx element from parent merk: {e}"
                ))
            })
        );
        match element.underlying() {
            Element::CountIndexedTree(_, secondary, ..)
            | Element::ProvableCountIndexedTree(_, secondary, ..) => {
                Ok(secondary.clone()).wrap_with_cost(cost)
            }
            _ => Err(Error::InvalidPath(
                "path's last segment is not a CountIndexedTree element".to_string(),
            ))
            .wrap_with_cost(cost),
        }
    }

    /// Verify a count-indexed top-k / range proof produced by
    /// [`Self::prove_count_indexed_top_k`]. Returns the GroveDB root
    /// hash this proof reconstructs together with the proven entries.
    ///
    /// The caller MUST supply `expected_k` and `expected_descending`
    /// matching the request that produced the proof. The verifier
    /// authenticates these against the envelope so a malicious prover
    /// cannot answer a `(k=10, descending=true)` request with a valid
    /// `(k=5, descending=false)` proof — both could chain to the same
    /// GroveDB root via the same path but expose different content.
    pub fn verify_count_indexed_top_k(
        proof_bytes: &[u8],
        path: &[&[u8]],
        expected_k: u16,
        expected_descending: bool,
    ) -> Result<CountIndexedQueryResult, Error> {
        // Bound the decode to a sane upper limit so adversarial input
        // claiming a huge Vec length can't trigger a capacity-overflow
        // panic in `Vec::with_capacity`. 16 MiB is far above any
        // legitimate cidx proof; bincode's `with_limit` rejects inputs
        // that would decode to more than this many bytes, including
        // Vec lengths that imply oversize allocations.
        let config = bincode::config::standard().with_limit::<{ 16 * 1024 * 1024 }>();
        let (envelope, _): (CountIndexedRangeProof, _) =
            bincode::decode_from_slice(proof_bytes, config)
                .map_err(|e| Error::CorruptedData(format!("decoding cidx proof: {e}")))?;
        // Authenticate caller intent. Reject envelopes whose semantics
        // don't match the request before doing any further work.
        if envelope.descending != expected_descending {
            return Err(Error::CorruptedData(format!(
                "cidx top_k proof direction mismatch: expected descending={}, envelope \
                 carries descending={}",
                expected_descending, envelope.descending
            )));
        }
        if envelope.requested_limit != Some(expected_k) {
            return Err(Error::CorruptedData(format!(
                "cidx top_k proof limit mismatch: expected Some({}), envelope carries {:?}",
                expected_k, envelope.requested_limit
            )));
        }
        let mut full_range = MerkQuery::new();
        full_range.insert_all();
        full_range.left_to_right = !envelope.descending;
        Self::verify_count_indexed_inner(envelope, full_range, path)
    }

    /// Verify a proof produced by [`Self::prove_count_indexed_query`].
    ///
    /// `secondary_query` must match the query supplied at proof time
    /// (positional binding: the merk proof's encoded sequence is
    /// query-shape-dependent). `expected_limit` must match the limit
    /// supplied at proof time; an envelope claiming a different limit
    /// is rejected. `None` and `Some(0)` are distinct.
    pub fn verify_count_indexed_query(
        proof_bytes: &[u8],
        secondary_query: MerkQuery,
        expected_limit: Option<u16>,
        path: &[&[u8]],
    ) -> Result<CountIndexedQueryResult, Error> {
        // Bound the decode to a sane upper limit so adversarial input
        // claiming a huge Vec length can't trigger a capacity-overflow
        // panic in `Vec::with_capacity`. 16 MiB is far above any
        // legitimate cidx proof; bincode's `with_limit` rejects inputs
        // that would decode to more than this many bytes, including
        // Vec lengths that imply oversize allocations.
        let config = bincode::config::standard().with_limit::<{ 16 * 1024 * 1024 }>();
        let (envelope, _): (CountIndexedRangeProof, _) =
            bincode::decode_from_slice(proof_bytes, config)
                .map_err(|e| Error::CorruptedData(format!("decoding cidx proof: {e}")))?;
        // Authenticate the limit. (Direction is authenticated by the
        // secondary_query's `left_to_right` field through merk's
        // positional binding — the envelope's `descending` is
        // informational here. We still check it for symmetry with
        // top_k so subtle bugs in the caller-supplied query don't
        // silently pass.)
        if envelope.requested_limit != expected_limit {
            return Err(Error::CorruptedData(format!(
                "cidx query proof limit mismatch: expected {:?}, envelope carries {:?}",
                expected_limit, envelope.requested_limit
            )));
        }
        let expected_descending = !secondary_query.left_to_right;
        if envelope.descending != expected_descending {
            return Err(Error::CorruptedData(format!(
                "cidx query proof direction mismatch: secondary_query implies \
                 descending={}, envelope carries descending={}",
                expected_descending, envelope.descending
            )));
        }
        Self::verify_count_indexed_inner(envelope, secondary_query, path)
    }

    /// Verify a proof produced by
    /// [`Self::prove_count_indexed_top_k_paginated`].
    ///
    /// `expected_k`, `expected_offset`, `expected_descending` MUST
    /// match the request that produced the proof. The verifier
    /// authenticates the echoed fields in the envelope against these
    /// before doing any merk-level work, so a malicious prover cannot
    /// answer a `(k=10, offset=20)` request with a valid
    /// `(k=5, offset=0)` proof.
    ///
    /// On success, `CountIndexedPaginatedResult.skipped` reports the
    /// number of secondary entries the proof committed as skipped
    /// (independently re-derived by the verifier from the merk proof
    /// shape — NOT trusted from the prover's echoed `requested_offset`).
    /// The caller MUST cross-check `skipped == expected_offset` if
    /// exact-page semantics matter — see the doc comment on
    /// `CountIndexedPaginatedResult.skipped`.
    pub fn verify_count_indexed_top_k_paginated(
        proof_bytes: &[u8],
        path: &[&[u8]],
        expected_k: u16,
        expected_offset: u64,
        expected_descending: bool,
    ) -> Result<CountIndexedPaginatedResult, Error> {
        // Same DoS bound as the other cidx verifiers; cf. comment on
        // `verify_count_indexed_top_k`.
        let config = bincode::config::standard().with_limit::<{ 16 * 1024 * 1024 }>();
        let (envelope, _): (CountIndexedPaginatedProof, _) =
            bincode::decode_from_slice(proof_bytes, config)
                .map_err(|e| Error::CorruptedData(format!("decoding cidx paginated proof: {e}")))?;

        // Authenticate the caller's intent against the envelope BEFORE
        // any merk-level work. A mismatch here means the envelope
        // describes a different page than the caller asked for; the
        // proof might still verify cryptographically but it's not
        // answering the right question.
        if envelope.descending != expected_descending {
            return Err(Error::CorruptedData(format!(
                "cidx paginated proof direction mismatch: expected descending={}, envelope \
                 carries descending={}",
                expected_descending, envelope.descending
            )));
        }
        if envelope.requested_k != expected_k {
            return Err(Error::CorruptedData(format!(
                "cidx paginated proof k mismatch: expected {}, envelope carries {}",
                expected_k, envelope.requested_k
            )));
        }
        if envelope.requested_offset != expected_offset {
            return Err(Error::CorruptedData(format!(
                "cidx paginated proof offset mismatch: expected {}, envelope carries {}",
                expected_offset, envelope.requested_offset
            )));
        }

        Self::verify_count_indexed_paginated_inner(envelope, path)
    }

    /// Shared verifier core for the paginated cidx proof. Same shape
    /// as [`Self::verify_count_indexed_inner`] — walks layer proofs
    /// bottom-up to authenticate the cidx element's H1-A composition —
    /// but the secondary proof is decoded via
    /// `verify_count_offset_on_range_proof` instead of the regular
    /// merk `execute_proof`.
    fn verify_count_indexed_paginated_inner(
        envelope: CountIndexedPaginatedProof,
        path: &[&[u8]],
    ) -> Result<CountIndexedPaginatedResult, Error> {
        use grovedb_merk::proofs::query::{
            verify_count_offset_on_range_proof, QueryItem as MerkQueryItemForRange,
        };

        if envelope.layer_proofs.len() != path.len() {
            return Err(Error::CorruptedData(format!(
                "cidx paginated proof has {} layers but path has {} segments",
                envelope.layer_proofs.len(),
                path.len()
            )));
        }
        if envelope.layer_proofs.is_empty() {
            return Err(Error::CorruptedData(
                "cidx paginated proof has zero layers; expected at least one (the path to the \
                 cidx element)"
                    .to_string(),
            ));
        }

        // 1a. Verify the secondary count-offset paginated proof.
        let inner_range = MerkQueryItemForRange::RangeFull(std::ops::RangeFull);
        let count_offset_result = verify_count_offset_on_range_proof(
            &envelope.secondary_proof,
            &inner_range,
            envelope.requested_offset,
            Some(envelope.requested_k as u64),
            !envelope.descending,
        )
        .unwrap()
        .map_err(|e| {
            Error::CorruptedData(format!(
                "cidx paginated proof: secondary count-offset proof failed to verify: {e}"
            ))
        })?;

        let secondary_root_hash = count_offset_result.root_hash;
        let mut entries: Vec<(u64, Vec<u8>)> =
            Vec::with_capacity(count_offset_result.returned_items.len());
        for proved in &count_offset_result.returned_items {
            // Secondary keys are (count_be ‖ original_key); the merk
            // prover preserves the on-disk key bytes verbatim.
            if proved.key.len() < 8 {
                return Err(Error::CorruptedData(format!(
                    "cidx paginated proof: secondary key shorter than 8 bytes: {:?}",
                    proved.key
                )));
            }
            let mut count_bytes = [0u8; 8];
            count_bytes.copy_from_slice(&proved.key[..8]);
            let count = u64::from_be_bytes(count_bytes);
            entries.push((count, proved.key[8..].to_vec()));
        }

        // 1b. Verify the deepest layer (cidx element) using H1-A.
        let last_idx = envelope.layer_proofs.len() - 1;
        let cidx_key = path[last_idx];
        let (cidx_value_bytes, mut current_layer_root, cidx_value_hash_recorded) =
            execute_single_key_proof(
                &envelope.layer_proofs[last_idx],
                cidx_key,
                "cidx paginated layer",
            )?;
        let actual_value_hash = value_hash(&cidx_value_bytes).value().to_owned();
        let combined = combine_hash_three(
            &actual_value_hash,
            &envelope.primary_root_hash,
            &secondary_root_hash,
        )
        .value()
        .to_owned();
        if combined != cidx_value_hash_recorded {
            return Err(Error::CorruptedData(format!(
                "cidx paginated proof: layer chain mismatch — parent recorded value_hash {} \
                 but combine_hash_three(H(cidx_bytes), primary_root, secondary_root) is {}",
                hex::encode(cidx_value_hash_recorded),
                hex::encode(combined)
            )));
        }

        // 1c. Walk shallower layers — identical shape to the
        // non-paginated verifier.
        if envelope.ancestor_cidx_secondary_root_hashes.len() != last_idx {
            return Err(Error::CorruptedData(format!(
                "cidx paginated proof: ancestor_cidx_secondary_root_hashes has length {} but \
                 expected {}",
                envelope.ancestor_cidx_secondary_root_hashes.len(),
                last_idx
            )));
        }
        for depth in (0..last_idx).rev() {
            let key = path[depth];
            let (value_bytes, layer_root, recorded_value_hash) = execute_single_key_proof(
                &envelope.layer_proofs[depth],
                key,
                "cidx paginated intermediate layer",
            )?;
            let val_h = value_hash(&value_bytes).value().to_owned();
            let combined = match envelope.ancestor_cidx_secondary_root_hashes[depth] {
                Some(ancestor_secondary_root) => {
                    combine_hash_three(&val_h, &current_layer_root, &ancestor_secondary_root)
                        .value()
                        .to_owned()
                }
                None => combine_hash(&val_h, &current_layer_root).value().to_owned(),
            };
            if combined != recorded_value_hash {
                let chain_kind = if envelope.ancestor_cidx_secondary_root_hashes[depth].is_some() {
                    "combine_hash_three"
                } else {
                    "combine_hash"
                };
                return Err(Error::CorruptedData(format!(
                    "cidx paginated proof: intermediate layer at depth {} chain mismatch: \
                     parent recorded value_hash {} but {}(H(value), child_root, ...) is {}",
                    depth,
                    hex::encode(recorded_value_hash),
                    chain_kind,
                    hex::encode(combined)
                )));
            }
            current_layer_root = layer_root;
        }

        Ok(CountIndexedPaginatedResult {
            root_hash: current_layer_root,
            entries,
            skipped: count_offset_result.skipped,
        })
    }

    fn verify_count_indexed_inner(
        envelope: CountIndexedRangeProof,
        secondary_query: MerkQuery,
        path: &[&[u8]],
    ) -> Result<CountIndexedQueryResult, Error> {
        if envelope.layer_proofs.len() != path.len() {
            return Err(Error::CorruptedData(format!(
                "cidx proof has {} layers but path has {} segments",
                envelope.layer_proofs.len(),
                path.len()
            )));
        }
        // Guard against an adversarial envelope claiming zero layers
        // (path also empty by the equality check above). `last_idx =
        // layer_proofs.len() - 1` would underflow on usize; the
        // resulting `usize::MAX` indexing into `path` / `layer_proofs`
        // panics. This is a DoS vector against any process calling
        // verify_count_indexed_top_k / verify_count_indexed_query on
        // attacker-controlled bytes (caught by the fuzz harness in
        // the cidx coverage tests; same class as the
        // capacity-overflow DoS fixed via `with_limit::<16 MiB>()`).
        if envelope.layer_proofs.is_empty() {
            return Err(Error::CorruptedData(
                "cidx proof has zero layers; expected at least one (the path to the \
                 cidx element)"
                    .to_string(),
            ));
        }

        // 1. Walk layer proofs bottom-up.
        //
        //    The deepest layer (last) proves the cidx element's existence
        //    in its parent Merk; the value_hash recorded for the cidx key
        //    must equal `combine_hash_three(H(cidx_bytes),
        //    primary_root_hash, secondary_root_hash)`.
        //
        //    Each shallower layer's element value_hash must equal
        //    `combine_hash(H(child_bytes), child_root_hash)`.

        // 1a. Verify the secondary range proof first (no chain dep).
        // `requested_limit` is now an explicit Option<u16>; pass it
        // through unchanged (no None↔0 conflation).
        let limit_for_verify = envelope.requested_limit;
        let left_to_right = secondary_query.left_to_right;
        let (secondary_root_hash, sec_result) = secondary_query
            .execute_proof(
                &envelope.secondary_proof,
                limit_for_verify,
                left_to_right,
                0,
            )
            .unwrap()
            .map_err(|e| {
                Error::CorruptedData(format!("secondary range proof failed to verify: {e}"))
            })?;

        let mut entries: Vec<(u64, Vec<u8>)> = Vec::with_capacity(sec_result.result_set.len());
        for proved in sec_result.result_set {
            if proved.key.len() < 8 {
                return Err(Error::CorruptedData(format!(
                    "secondary key is shorter than 8 bytes: {:?}",
                    proved.key
                )));
            }
            let mut count_bytes = [0u8; 8];
            count_bytes.copy_from_slice(&proved.key[..8]);
            let count = u64::from_be_bytes(count_bytes);
            entries.push((count, proved.key[8..].to_vec()));
        }

        // 1b. Verify the deepest layer (cidx element) using H1-A.
        let last_idx = envelope.layer_proofs.len() - 1;
        let cidx_key = path[last_idx];
        let (cidx_value_bytes, mut current_layer_root, cidx_value_hash_recorded) =
            execute_single_key_proof(&envelope.layer_proofs[last_idx], cidx_key, "cidx layer")?;
        let actual_value_hash = value_hash(&cidx_value_bytes).value().to_owned();
        let combined = combine_hash_three(
            &actual_value_hash,
            &envelope.primary_root_hash,
            &secondary_root_hash,
        )
        .value()
        .to_owned();
        if combined != cidx_value_hash_recorded {
            return Err(Error::CorruptedData(format!(
                "cidx layer chain mismatch: parent recorded value_hash {} but \
                 combine_hash_three(H(cidx_bytes), primary_root, secondary_root) is {}",
                hex::encode(cidx_value_hash_recorded),
                hex::encode(combined)
            )));
        }

        // 1c. Walk shallower layers. Each layer chains via either
        //     `combine_hash` (regular tree ancestor) or
        //     `combine_hash_three` (cidx ancestor — uses
        //     `current_layer_root` as primary_root and the per-layer
        //     attestation as secondary_root).
        if envelope.ancestor_cidx_secondary_root_hashes.len() != last_idx {
            return Err(Error::CorruptedData(format!(
                "ancestor_cidx_secondary_root_hashes has length {} but expected {}",
                envelope.ancestor_cidx_secondary_root_hashes.len(),
                last_idx
            )));
        }
        for depth in (0..last_idx).rev() {
            let key = path[depth];
            let (value_bytes, layer_root, recorded_value_hash) =
                execute_single_key_proof(&envelope.layer_proofs[depth], key, "intermediate layer")?;
            let val_h = value_hash(&value_bytes).value().to_owned();
            let combined = match envelope.ancestor_cidx_secondary_root_hashes[depth] {
                Some(ancestor_secondary_root) => {
                    combine_hash_three(&val_h, &current_layer_root, &ancestor_secondary_root)
                        .value()
                        .to_owned()
                }
                None => combine_hash(&val_h, &current_layer_root).value().to_owned(),
            };
            if combined != recorded_value_hash {
                let chain_kind = if envelope.ancestor_cidx_secondary_root_hashes[depth].is_some() {
                    "combine_hash_three(H(value), primary_root, secondary_root)"
                } else {
                    "combine_hash(H(value), child_root)"
                };
                return Err(Error::CorruptedData(format!(
                    "intermediate layer chain mismatch at depth {}: parent recorded \
                     value_hash {} but {} is {}",
                    depth,
                    hex::encode(recorded_value_hash),
                    chain_kind,
                    hex::encode(combined)
                )));
            }
            current_layer_root = layer_root;
        }

        Ok(CountIndexedQueryResult {
            root_hash: current_layer_root,
            entries,
        })
    }
}

/// Verify a single-key Merk proof: returns
/// `(value_bytes, layer_root_hash, parent_recorded_value_hash)`.
fn execute_single_key_proof(
    proof_bytes: &[u8],
    target_key: &[u8],
    layer_label: &'static str,
) -> Result<(Vec<u8>, CryptoHash, CryptoHash), Error> {
    let mut query = MerkQuery::new();
    query.insert_item(MerkQueryItem::Key(target_key.to_vec()));
    let (root_hash, result) = query
        .execute_proof(proof_bytes, None, true, 0)
        .unwrap()
        .map_err(|e| {
            Error::CorruptedData(format!(
                "{layer_label} single-key proof for {} failed to verify: {e}",
                hex::encode(target_key)
            ))
        })?;
    let proved = result
        .result_set
        .iter()
        .find(|p| p.key == target_key)
        .ok_or_else(|| {
            Error::CorruptedData(format!(
                "{layer_label} proof did not contain expected key {}",
                hex::encode(target_key)
            ))
        })?;
    let value = proved.value.clone().ok_or_else(|| {
        Error::CorruptedData(format!(
            "{layer_label} proof for key {} returned no value bytes",
            hex::encode(target_key)
        ))
    })?;
    Ok((value, root_hash, proved.proof))
}
