//! Proof generation and verification for `CountIndexedTree` top-k and
//! count-range queries.
//!
//! The proof envelope binds three pieces:
//! 1. A chain of single-key Merk proofs from the GroveDB root down to the
//!    parent Merk of the `CountIndexedTree` element, ending with a proof
//!    of the cidx element's existence.
//! 2. A 32-byte attestation of the cidx primary's root hash. The primary
//!    is not traversed by these queries, but its root hash participates in
//!    the H1-A `combined_value_hash` of the cidx element and so must be
//!    available to the verifier.
//! 3. A standard Merk range proof against the cidx **secondary**, which
//!    yields the top-k / range entries and the secondary's root hash.
//!
//! The verifier reconstructs
//! `combine_hash_three(value_hash(cidx_element_bytes), primary_root_hash,
//! secondary_root_hash)` and checks it equals the value_hash recorded for
//! the cidx key by its parent Merk. That single check binds the secondary
//! range proof to the GroveDB root hash via the H1-A composition we
//! ratified in design (chapter "The CountIndexedTree", H1-A).
//!
//! No batch / cross-subtree integration with the existing GroveDBProof
//! envelope yet — this is a standalone proof shape, decoded only by the
//! dedicated `verify_count_indexed_*` entry points.

use bincode::{Decode, Encode};
use grovedb_costs::{
    cost_return_on_error, cost_return_on_error_no_add, CostResult, CostsExt, OperationCost,
};
use grovedb_merk::{
    element::get::ElementFetchFromStorageExtensions,
    proofs::{query::QueryProofVerify, Query as MerkQuery},
    tree::{combine_hash, combine_hash_three, value_hash, CryptoHash},
};
use grovedb_path::{SubtreePath, SubtreePathBuilder};
use grovedb_query::QueryItem as MerkQueryItem;
use grovedb_storage::StorageBatch;
use grovedb_version::version::GroveVersion;

use crate::{util::TxRef, Element, Error, GroveDb, Transaction, TransactionArg};

/// Wire-format envelope for a `CountIndexedTree` top-k / count-range
/// proof. Layered proofs (`layer_proofs[i]`) walk the GroveDB hierarchy
/// from the root toward the cidx element; `layer_proofs.last()` is the
/// deepest single-key proof, which proves the cidx element's existence
/// in its parent Merk.
#[derive(Encode, Decode, Debug)]
pub struct CountIndexedRangeProof {
    /// Single-key Merk proof per path layer, top-down.
    /// `layer_proofs[i]` is generated by opening the Merk at `path[..i]`
    /// and proving the existence of `path[i]`.
    pub layer_proofs: Vec<Vec<u8>>,
    /// 32-byte attestation of the cidx primary's root hash. Carried by
    /// the proof because the verifier needs it to reconstruct the H1-A
    /// composition but does not traverse the primary itself.
    pub primary_root_hash: [u8; 32],
    /// Per-intermediate-layer cidx secondary attestation, length =
    /// `layer_proofs.len() - 1`. For depth `d` in
    /// `0..layer_proofs.len() - 1`, `Some(secondary_root_hash)` means
    /// the element at `path[..d+1]` is itself a cidx — its merk node's
    /// `value_hash` was composed with `combine_hash_three(value_hash,
    /// primary_root, secondary_root)`. The verifier uses
    /// `current_layer_root` (root hash of layer `d+1`'s merk) as the
    /// primary_root and this attestation as the secondary_root.
    /// `None` means the layer's element is a regular tree and chains
    /// via the standard `combine_hash`.
    pub ancestor_cidx_secondary_root_hashes: Vec<Option<[u8; 32]>>,
    /// Encoded Merk range proof for the cidx secondary. Verified
    /// independently with the existing `Query::execute_proof` API; yields
    /// the secondary's root hash and the (count_be ‖ key) entries.
    pub secondary_proof: Vec<u8>,
    /// Echoed query parameters (used by the verifier to interpret /
    /// validate the secondary proof).
    pub requested_limit: u16,
    pub descending: bool,
}

/// Verified result of a `CountIndexedTree` top-k or count-range query.
#[derive(Debug)]
pub struct CountIndexedQueryResult {
    /// GroveDB root hash this proof reconstructs.
    pub root_hash: CryptoHash,
    /// `(count_value, original_key)` pairs from the secondary, in the
    /// order they were proven. Caller is responsible for any further
    /// limit/range filtering beyond what the proof carries.
    pub entries: Vec<(u64, Vec<u8>)>,
}

impl GroveDb {
    /// Generate a proof for the top-`k` entries of a `CountIndexedTree`,
    /// ordered by `count_value`.
    pub fn prove_count_indexed_top_k<'b, B, P>(
        &self,
        path: P,
        k: u16,
        descending: bool,
        transaction: TransactionArg,
        grove_version: &GroveVersion,
    ) -> CostResult<Vec<u8>, Error>
    where
        B: AsRef<[u8]> + 'b,
        P: Into<SubtreePath<'b, B>>,
    {
        let mut cost = OperationCost::default();
        let path: SubtreePath<B> = path.into();
        let batch = StorageBatch::new();
        let tx = TxRef::new(&self.db, transaction);
        let tx_ref = tx.as_ref();

        let envelope = cost_return_on_error!(
            &mut cost,
            self.build_count_indexed_proof(path, k, descending, tx_ref, &batch, grove_version)
        );

        let bytes = cost_return_on_error_no_add!(
            cost,
            bincode::encode_to_vec(&envelope, bincode::config::standard())
                .map_err(|e| Error::CorruptedData(format!("encoding cidx proof: {e}")))
        );

        Ok(bytes).wrap_with_cost(cost)
    }

    fn build_count_indexed_proof<'db, 'b, B: AsRef<[u8]>>(
        &'db self,
        path: SubtreePath<'b, B>,
        k: u16,
        descending: bool,
        transaction: &'db Transaction,
        batch: &'db StorageBatch,
        grove_version: &GroveVersion,
    ) -> CostResult<CountIndexedRangeProof, Error> {
        let mut cost = OperationCost::default();

        // Collect path keys and parent paths for layer-by-layer proof.
        let path_keys: Vec<Vec<u8>> = path.to_vec();
        if path_keys.is_empty() {
            return Err(Error::InvalidPath(
                "cannot prove count-indexed query at root path".to_string(),
            ))
            .wrap_with_cost(cost);
        }

        // 1. Build a single-key Merk proof at each layer (top-down).
        //
        //    For each intermediate depth `d` (`d < last_idx`), if the
        //    element at `path[..d+1]` is itself a CountIndexedTree,
        //    capture its secondary root hash as an attestation; the
        //    verifier needs it to chain via `combine_hash_three` at that
        //    layer (cidx ancestors compose with three inputs, not two).
        let mut layer_proofs: Vec<Vec<u8>> = Vec::with_capacity(path_keys.len());
        let last_idx = path_keys.len() - 1;
        let mut ancestor_cidx_secondary_root_hashes: Vec<Option<[u8; 32]>> =
            Vec::with_capacity(last_idx);
        for depth in 0..path_keys.len() {
            // The Merk at path[..depth] proves the existence of
            // path_keys[depth].
            let parent_slices: Vec<&[u8]> =
                path_keys[..depth].iter().map(|p| p.as_slice()).collect();
            let parent_path: SubtreePath<&[u8]> = parent_slices.as_slice().into();
            let parent_merk = cost_return_on_error!(
                &mut cost,
                self.open_transactional_merk_at_path(
                    parent_path.clone(),
                    transaction,
                    Some(batch),
                    grove_version,
                )
            );
            let key = path_keys[depth].clone();
            if depth < last_idx {
                let intermediate = cost_return_on_error!(
                    &mut cost,
                    Element::get(&parent_merk, key.as_slice(), true, grove_version)
                        .map_err(Error::MerkError)
                );
                let attestation = match intermediate.underlying() {
                    Element::CountIndexedTree(..) | Element::ProvableCountIndexedTree(..) => {
                        // Open this ancestor cidx's secondary and capture
                        // its current root hash for the attestation.
                        let ancestor_cidx_path_owned: SubtreePathBuilder<Vec<u8>> =
                            SubtreePathBuilder::owned_from_iter(
                                path_keys[..=depth].iter().cloned(),
                            );
                        let ancestor_cidx_path = SubtreePath::from(&ancestor_cidx_path_owned);
                        let ancestor_secondary_root_key = match intermediate.underlying() {
                            Element::CountIndexedTree(_, s, ..)
                            | Element::ProvableCountIndexedTree(_, s, ..) => s.clone(),
                            _ => unreachable!(),
                        };
                        let ancestor_secondary = cost_return_on_error!(
                            &mut cost,
                            self.open_count_indexed_secondary_at_path(
                                ancestor_cidx_path,
                                ancestor_secondary_root_key,
                                transaction,
                                Some(batch),
                                grove_version,
                            )
                        );
                        let (sec_hash, _, _) = cost_return_on_error!(
                            &mut cost,
                            ancestor_secondary
                                .root_hash_key_and_aggregate_data()
                                .map_err(Error::MerkError)
                        );
                        Some(sec_hash)
                    }
                    _ => None,
                };
                ancestor_cidx_secondary_root_hashes.push(attestation);
            }
            let mut q = MerkQuery::new();
            q.insert_item(MerkQueryItem::Key(key));
            let result = cost_return_on_error!(
                &mut cost,
                parent_merk
                    .prove(q, None, grove_version)
                    .map_err(Error::MerkError)
            );
            layer_proofs.push(result.proof);
        }

        // 2. Open primary at path; capture its root hash for attestation.
        let primary_merk = cost_return_on_error!(
            &mut cost,
            self.open_transactional_merk_at_path(
                path.clone(),
                transaction,
                Some(batch),
                grove_version,
            )
        );
        if !primary_merk.tree_type.is_count_indexed_primary() {
            return Err(Error::InvalidPath(
                "prove_count_indexed_top_k requires the path's last segment to be a \
                 CountIndexedTree element"
                    .to_string(),
            ))
            .wrap_with_cost(cost);
        }
        let (primary_root_hash, _, _) = cost_return_on_error!(
            &mut cost,
            primary_merk
                .root_hash_key_and_aggregate_data()
                .map_err(Error::MerkError)
        );

        // 3. Open secondary; produce a range proof in the requested
        //    direction with limit = k.
        let secondary_root_key = cost_return_on_error!(
            &mut cost,
            self.read_count_indexed_secondary_root_key_for_proof(
                path.clone(),
                transaction,
                Some(batch),
                grove_version,
            )
        );
        let secondary_merk = cost_return_on_error!(
            &mut cost,
            self.open_count_indexed_secondary_at_path(
                path,
                secondary_root_key,
                transaction,
                Some(batch),
                grove_version,
            )
        );
        let mut sec_query = MerkQuery::new();
        sec_query.insert_all();
        sec_query.left_to_right = !descending;
        let sec_result = cost_return_on_error!(
            &mut cost,
            secondary_merk
                .prove(sec_query, Some(k), grove_version)
                .map_err(Error::MerkError)
        );

        Ok(CountIndexedRangeProof {
            layer_proofs,
            primary_root_hash,
            ancestor_cidx_secondary_root_hashes,
            secondary_proof: sec_result.proof,
            requested_limit: k,
            descending,
        })
        .wrap_with_cost(cost)
    }

    fn read_count_indexed_secondary_root_key_for_proof<'db, 'b, B: AsRef<[u8]>>(
        &'db self,
        path: SubtreePath<'b, B>,
        transaction: &'db Transaction,
        batch: Option<&'db StorageBatch>,
        grove_version: &GroveVersion,
    ) -> CostResult<Option<Vec<u8>>, Error> {
        let mut cost = OperationCost::default();
        let (parent_path, count_indexed_key) = match path.derive_parent() {
            Some(p) => p,
            None => {
                return Err(Error::InvalidPath(
                    "cannot prove count-indexed query at root path".to_string(),
                ))
                .wrap_with_cost(cost);
            }
        };
        let parent_merk = cost_return_on_error!(
            &mut cost,
            self.open_transactional_merk_at_path(parent_path, transaction, batch, grove_version)
        );
        let element = cost_return_on_error!(
            &mut cost,
            Element::get(&parent_merk, count_indexed_key, true, grove_version)
                .map_err(Error::MerkError)
        );
        match element.underlying() {
            Element::CountIndexedTree(_, secondary, ..)
            | Element::ProvableCountIndexedTree(_, secondary, ..) => {
                Ok(secondary.clone()).wrap_with_cost(cost)
            }
            _ => Err(Error::InvalidPath(
                "path's last segment is not a CountIndexedTree element".to_string(),
            ))
            .wrap_with_cost(cost),
        }
    }

    /// Verify a count-indexed top-k / range proof produced by
    /// [`Self::prove_count_indexed_top_k`]. Returns the GroveDB root
    /// hash this proof reconstructs together with the proven entries.
    pub fn verify_count_indexed_top_k(
        proof_bytes: &[u8],
        path: &[&[u8]],
    ) -> Result<CountIndexedQueryResult, Error> {
        let (envelope, _): (CountIndexedRangeProof, _) =
            bincode::decode_from_slice(proof_bytes, bincode::config::standard())
                .map_err(|e| Error::CorruptedData(format!("decoding cidx proof: {e}")))?;

        if envelope.layer_proofs.len() != path.len() {
            return Err(Error::CorruptedData(format!(
                "cidx proof has {} layers but path has {} segments",
                envelope.layer_proofs.len(),
                path.len()
            )));
        }

        // 1. Walk layer proofs bottom-up.
        //
        //    The deepest layer (last) proves the cidx element's existence
        //    in its parent Merk; the value_hash recorded for the cidx key
        //    must equal `combine_hash_three(H(cidx_bytes),
        //    primary_root_hash, secondary_root_hash)`.
        //
        //    Each shallower layer's element value_hash must equal
        //    `combine_hash(H(child_bytes), child_root_hash)`.

        // 1a. Verify the secondary range proof first (no chain dep).
        let mut sec_query = MerkQuery::new();
        sec_query.insert_all();
        sec_query.left_to_right = !envelope.descending;
        let (secondary_root_hash, sec_result) = sec_query
            .execute_proof(
                &envelope.secondary_proof,
                Some(envelope.requested_limit),
                !envelope.descending,
                0,
            )
            .unwrap()
            .map_err(|e| {
                Error::CorruptedData(format!("secondary range proof failed to verify: {e}"))
            })?;

        let mut entries: Vec<(u64, Vec<u8>)> = Vec::with_capacity(sec_result.result_set.len());
        for proved in sec_result.result_set {
            if proved.key.len() < 8 {
                return Err(Error::CorruptedData(format!(
                    "secondary key is shorter than 8 bytes: {:?}",
                    proved.key
                )));
            }
            let mut count_bytes = [0u8; 8];
            count_bytes.copy_from_slice(&proved.key[..8]);
            let count = u64::from_be_bytes(count_bytes);
            entries.push((count, proved.key[8..].to_vec()));
        }

        // 1b. Verify the deepest layer (cidx element) using H1-A.
        let last_idx = envelope.layer_proofs.len() - 1;
        let cidx_key = path[last_idx];
        let (cidx_value_bytes, mut current_layer_root, cidx_value_hash_recorded) =
            execute_single_key_proof(&envelope.layer_proofs[last_idx], cidx_key, "cidx layer")?;
        let actual_value_hash = value_hash(&cidx_value_bytes).value().to_owned();
        let combined = combine_hash_three(
            &actual_value_hash,
            &envelope.primary_root_hash,
            &secondary_root_hash,
        )
        .value()
        .to_owned();
        if combined != cidx_value_hash_recorded {
            return Err(Error::CorruptedData(format!(
                "cidx layer chain mismatch: parent recorded value_hash {} but \
                 combine_hash_three(H(cidx_bytes), primary_root, secondary_root) is {}",
                hex::encode(cidx_value_hash_recorded),
                hex::encode(combined)
            )));
        }

        // 1c. Walk shallower layers. Each layer chains via either
        //     `combine_hash` (regular tree ancestor) or
        //     `combine_hash_three` (cidx ancestor — uses
        //     `current_layer_root` as primary_root and the per-layer
        //     attestation as secondary_root).
        if envelope.ancestor_cidx_secondary_root_hashes.len() != last_idx {
            return Err(Error::CorruptedData(format!(
                "ancestor_cidx_secondary_root_hashes has length {} but expected {}",
                envelope.ancestor_cidx_secondary_root_hashes.len(),
                last_idx
            )));
        }
        for depth in (0..last_idx).rev() {
            let key = path[depth];
            let (value_bytes, layer_root, recorded_value_hash) =
                execute_single_key_proof(&envelope.layer_proofs[depth], key, "intermediate layer")?;
            let val_h = value_hash(&value_bytes).value().to_owned();
            let combined = match envelope.ancestor_cidx_secondary_root_hashes[depth] {
                Some(ancestor_secondary_root) => {
                    combine_hash_three(&val_h, &current_layer_root, &ancestor_secondary_root)
                        .value()
                        .to_owned()
                }
                None => combine_hash(&val_h, &current_layer_root).value().to_owned(),
            };
            if combined != recorded_value_hash {
                let chain_kind = if envelope.ancestor_cidx_secondary_root_hashes[depth].is_some() {
                    "combine_hash_three(H(value), primary_root, secondary_root)"
                } else {
                    "combine_hash(H(value), child_root)"
                };
                return Err(Error::CorruptedData(format!(
                    "intermediate layer chain mismatch at depth {}: parent recorded \
                     value_hash {} but {} is {}",
                    depth,
                    hex::encode(recorded_value_hash),
                    chain_kind,
                    hex::encode(combined)
                )));
            }
            current_layer_root = layer_root;
        }

        Ok(CountIndexedQueryResult {
            root_hash: current_layer_root,
            entries,
        })
    }
}

/// Verify a single-key Merk proof: returns
/// `(value_bytes, layer_root_hash, parent_recorded_value_hash)`.
fn execute_single_key_proof(
    proof_bytes: &[u8],
    target_key: &[u8],
    layer_label: &'static str,
) -> Result<(Vec<u8>, CryptoHash, CryptoHash), Error> {
    let mut query = MerkQuery::new();
    query.insert_item(MerkQueryItem::Key(target_key.to_vec()));
    let (root_hash, result) = query
        .execute_proof(proof_bytes, None, true, 0)
        .unwrap()
        .map_err(|e| {
            Error::CorruptedData(format!(
                "{layer_label} single-key proof for {} failed to verify: {e}",
                hex::encode(target_key)
            ))
        })?;
    let proved = result
        .result_set
        .iter()
        .find(|p| p.key == target_key)
        .ok_or_else(|| {
            Error::CorruptedData(format!(
                "{layer_label} proof did not contain expected key {}",
                hex::encode(target_key)
            ))
        })?;
    let value = proved.value.clone().ok_or_else(|| {
        Error::CorruptedData(format!(
            "{layer_label} proof for key {} returned no value bytes",
            hex::encode(target_key)
        ))
    })?;
    Ok((value, root_hash, proved.proof))
}
